[package]
name = "pointillism"
authors = ["Violeta Hern√°ndez <vi.hdz.p@gmail.com>"]
description = "Library for generating audio."
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/vihdzp/pointillism"
version = "0.1.1"

[dependencies]
hound = "3.5.0"
rand = "0.8.5"